version: '3'
services:
  voice-pro-service:
    image: afirezd/voice-pro:v0.1
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: ["gpu"]
    ports:
      - "7860:7860"
      - "8080:8080"
    ipc: host
    ulimits:
      memlock: -1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GRADIO_SERVER_NAME=0.0.0.0  # Gradio 配置1：允许外部访问
      - GRADIO_SERVER_PORT=7860     # Gradio 配置2：指定端口
    # volumes:
      # - ./tmp/app:/app # 1
      # - ./workspace:/workspace
    stdin_open: true
    tty: true
    # command: bash